ProbabilitiesWebCalculator/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using ProbabilitiesWebCalculator.Areas.HelpPage.ModelDescriptions;
using ProbabilitiesWebCalculator.Areas.HelpPage.Models;

namespace ProbabilitiesWebCalculator.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

ProbabilitiesWebCalculator/Views/Shared/_InputForm.cshtml
@model  ProbabilitiesWebCalculator.Models.ProbabilityCalculator
<div id="InputForm">
    @using (Html.BeginForm("CalculateResult", "Home", FormMethod.Post, new { id = "frmCalculator" }))
    {
        @Html.ValidationSummary(true)
        <div class="container">
            <fieldset>
                <legend>Probabilities Calculator</legend>
                <div class="form-group">

                    @Html.LabelFor(model => model.ProbabilityA, new { @class = "col-sm" })

                    @Html.EditorFor(model => model.ProbabilityA, new
               {
                   htmlAttributes = new
                   {
                       @class = "col-sm",
                       @id = "ProbabilityA"
                   }
               })
                    @Html.ValidationMessageFor(model => model.ProbabilityA)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ProbabilityB)
                    @Html.EditorFor(model => model.ProbabilityB, new
               {
                   htmlAttributes = new
                   {
                       @class = "col-sm",
                       @id = "ProbabilityB"
                   }
               })
                    @Html.ValidationMessageFor(model => model.ProbabilityB)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Mode)
                    @Html.EnumDropDownListFor(model => model.Mode, new
               {
                   htmlAttributes = new
                   {
                       @class = "col-sm",
                       @id = "Mode"
                   }
               })
                </div>
                @*<div class="form-group">
                         @Html.LabelFor(model => model.Result)
                         @Html.EditorFor(model => model.Result, new
                    {
                        htmlAttributes = new
                        {
                            @class = "col-sm",
                            @id = "Result",
                            disabled = "disabled",
                            @readonly = "readonly"
                        }
                    })
                     </div>*@
                <div>
                    <input type="button" value="Calculate" id="btnCalculate" class="btn btn-default" />
                </div>
            </fieldset>
        </div>
    }
</div>

ProbabilitiesWebCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Probabilities Calculator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProbabilitiesWebCalculator/Views/Shared/_displayHistory.cshtml
@model  PagedList.IPagedList<ProbabilitiesWebCalculator.Models.ProbabilityCalculator>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<div>

    <button id="btnDisplayForm" type="button" class="btn btn-Link"> Hide History Records</button>

    <div id="DisplayHistory">
        <div class="pagination">

            @Html.PagedListPager(Model, page => Url.Action("Index", new { page}))
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        </div>
        <table id="historyTable" class="table table-bordered table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <th>Count</th>
                    <th> @Html.ActionLink("CreatedAt", "Index", new { sortOrder = ViewBag.DateSortParm })</th>
                    <th>P(A)</th>
                    <th>P(B)</th>
                    <th> @Html.ActionLink("Mode", "Index", new { sortOrder = ViewBag.ModeSortParm })</th>
                    <th>Result</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <tr style="border:1px solid red">
                        <td>@((Model.PageNumber-1)*Model.PageSize + i+1)</td>
                        <td>@Model[i].CreatedAt</td>
                        <td>@Model[i].ProbabilityA</td>
                        <td>@Model[i].ProbabilityB</td>
                        <td>@Model[i].Mode</td>
                        <td>@Model[i].Result</td>
                    </tr>



                }
            </tbody>
        </table>
    </div>

</div>